logging:
    version: 1
    disable_existing_loggers: False
    formatters:
      brief:
        format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
      precise:
        format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'
    handlers:
      console:
        class : logging.StreamHandler
        formatter: brief
        level   : INFO
        stream  : ext://sys.stdout
      file:
        class : logging.handlers.RotatingFileHandler
        formatter: precise
        level   : DEBUG
        filename: detours.log
        maxBytes: 1024
        backupCount: 3
    root:
        level: DEBUG
        handlers: [console, file]
detours:
    io_providers:
        CloudProvider:
            name: aws
            provider: s3_us_west_oregon
            id: <PLACE YOUR ID HERE>
            key: <PLACE YOUR KEY HERE>
            container: detours
            path_prefix: /foo/bar/
        CloudProvider:
            name: google-cloud
            provider: google_storage
            id: <PLACE YOUR ID HERE>
            key: <PLACE YOUR KEY HERE>
            container: cloud-detours-test
            path_prefix: /foo/bar/
        LocalProvider:
            name: on-premise
            provider: 'Local FS'
            container: /tmp/detours/
            path_prefix: /foo/bar/