logging:
    version: 1
    disable_existing_loggers: False
    formatters:
      brief:
        format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
      precise:
        format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'
    handlers:
      console:
        class : logging.StreamHandler
        formatter: brief
        level   : INFO
        stream  : ext://sys.stdout
      file:
        class : logging.handlers.RotatingFileHandler
        formatter: precise
        level   : DEBUG
        filename: /tmp/detours/logs/detours.log
        maxBytes: 1024000
        backupCount: 3
    root:
        level: DEBUG
        handlers: [console, file]
detours:
    keys: '~/devel/keys.yaml'
    dispatch_layer: 'etc/dispatcher.yaml'
    dirs:
        - /tmp/detours
        - /tmp/detours/channels
        - /tmp/detours/container
        - /tmp/detours/logs